apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twg.fullname" . }}-transmission-settings
  labels:
    {{- include "twg.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- toJson .Values.transmission.settings | nindent 4 }}
