apiVersion: v1
kind: Service
metadata:
  name: {{ include "twg.fullname" . }}
  labels:
    {{- include "twg.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "twg.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
      protocol: TCP
    - name: peer-tcp
      port: {{ .Values.service.peerPortTcp }}
      targetPort: {{ .Values.service.peerPortTcp }}
      protocol: TCP
    - name: peer-udp
      port: {{ .Values.service.peerPortUdp }}
      targetPort: {{ .Values.service.peerPortUdp }}
      protocol: UDP
